AllCops:
  Exclude:
    - 'bin/*'
    - 'config/application.rb'
    - 'db/schema.rb'

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false