AllCops:
  Exclude:
    - 'bin/*'
    - 'config/application.rb'
    - 'db/**/*'

Metrics/LineLength:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false