# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

# Shared secrets are available across all environments.
shared:
  mbta_api_key: <%= ENV['MBTA_API_KEY'] %>
  google_api_key: <%= ENV['GOOGLE_API_KEY'] %>

development:
  secret_key_base: 9db9679ec555f84849a05511fa5b549050701422207a7160f47a964bb6120cd4ad55f87822b24c88b6f7a27dbc9739e1cbabc42951cf893e71af35da1ded73f8

test:
  secret_key_base: ad142c35890f6cb36600c83b8122be4dcf774becdef770a73fd61fcdd60dec8595948834c8beb321d9782db95cfccfb7c5b9d4366218d1506a606ff11d4edd4e

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
